name: Crime Report
favicon: null
layout_spectrum: 0.0780737642198801
typography_spectrum: 0.7616033039521426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6096135436091572
  lightness: 0.3675200310535729
  saturation: 0.33578066201880574
  rhythmicContrast: 0.027959077851846814
purpose: []
